#Aqui se guardan los personajes
import pygame
import os
from random import randint
CHARACTERS = [("Tailand","Sagat", pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat_photo.png'),
((pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/quieto.png'), pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/quieto_izq.png')),

((pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/caminar.png'),
                 pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/caminar1.png'),
                 pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/caminar2.png'),
                 pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/caminar3.png'),
                 pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/caminar4.png'),
                 pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/caminar5.png')),
 (pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/caminar_izq.png'),
  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/caminar1_izq.png'),
  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/caminar2_izq.png'),
  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/caminar3_izq.png'),
  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/caminar4_izq.png'),
  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/caminar5_izq.png'))),

 ((pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/salto1.png'),
  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/salto2.png'),
  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/salto2.png'),
  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/salto3.png')),
  (pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/salto1_izq.png'),
   pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/salto2_izq.png'),
   pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/salto2_izq.png'),
   pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/salto3_izq.png'))),

 ((pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/patada.png'),
  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/patada1.png'),
  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/patada2.png'),
  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/patada3.png'),
  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/patada4.png')),
  (pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/patada_izq.png'),
   pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/patada1_izq.png'),
   pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/patada2_izq.png'),
   pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/patada3_izq.png'),
   pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/patada4_izq.png'))),

 ((pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/puño.png'),
  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/puño1.png'),
  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/puño2.png')),
  (pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/puño_izq.png'),
   pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/puño1_izq.png'),
   pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/puño2_izq.png'))),
   
   ((pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/agacharse.png'),
    pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/agacharse1.png')),
    (pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/agacharse_izq.png'),
    pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/agacharse1_izq.png'))),
    ((pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/perdedor.png'),
                 pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/perdedor1.png'),
                 pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/perdedor2.png'),
                 pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/perdedor3.png'),
                 pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/perdedor4.png')),
 (pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/perdedor_izq.png'),
  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/perdedor1_izq.png'),
  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/perdedor2_izq.png'),
  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/perdedor3_izq.png'),
  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/perdedor4_izq.png'))),
  ((pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/victoria.png'),
                 pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/victoria1.png'),
                 pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/victoria2.png'),
                 pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/victoria3.png')),
   (pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/victoria_izq.png'),
    pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/victoria1_izq.png'),
    pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/victoria2_izq.png'),
    pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/sagat/victoria3_izq.png')))),{"heal": 1400, "kick": 13,"punch":5, "speed": 8}),
              ("Japan","Ryu", pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu_photo.png').convert(),
               ((pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/quieto.png'),
                 pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/quieto_izq.png')),

                ((pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/caminar.png'),
                  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/caminar1.png'),
                  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/caminar2.png'),
                  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/caminar3.png'),
                  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/caminar4.png'),
                  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/caminar5.png')),
                 (pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/caminar_izq.png'),
                  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/caminar1_izq.png'),
                  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/caminar2_izq.png'),
                  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/caminar3_izq.png'),
                  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/caminar4_izq.png'),
                  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/caminar5_izq.png'))),

                ((pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/salto1.png'),
                  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/salto2.png'),
                  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/salto2.png'),
                  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/salto3.png')),
                 (pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/salto1_izq.png'),
                  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/salto2_izq.png'),
                  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/salto2_izq.png'),
                  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/salto3_izq.png'))),

                ((pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/patada.png'),
                  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/patada1.png'),
                  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/patada2.png'),
                  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/patada3.png'),
                  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/patada4.png')),
                 (pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/patada_izq.png'),
                  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/patada1_izq.png'),
                  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/patada2_izq.png'),
                  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/patada3_izq.png'),
                  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/patada4_izq.png'))),

                ((pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/puño.png'),
                  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/puño1.png'),
                  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/puño2.png')),
                 (pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/puño_izq.png'),
                  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/puño1_izq.png'),
                  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/puño2_izq.png'))),
                  
                  ((pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/agacharse.png'),
                  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/agacharse1.png')),
                  (pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/agacharse_izq.png'),
                 pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/agacharse1_izq.png'))),
                 
                 ((pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/perdedor.png'),
                 pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/perdedor1.png'),
                 pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/perdedor2.png'),
                 pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/perdedor3.png'),
                 pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/perdedor4.png')),
 (pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/perdedor_izq.png'),
  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/perdedor1_izq.png'),
  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/perdedor2_izq.png'),
  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/perdedor3_izq.png'),
  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/perdedor4_izq.png'))),
  
  ((pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/victoria.png'),
                 pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/victoria1.png'),
                 pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/victoria2.png'),
                 pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/victoria3.png')),
 (pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/victoria_izq.png'),
  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/victoria1_izq.png'),
  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/victoria2_izq.png'),
  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/ryu/victoria3_izq.png')))),{"heal": 1350, "kick": 10,"punch":8, "speed": 10}),
              ("Japan", "Honda",
               pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/edmond_photo.png'),
               ((pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/edmond/quieto.png'),
                 pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/edmond/quieto_izq.png')),
                ((pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/edmond/caminar.png'),
                  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/edmond/caminar1.png'),
                  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/edmond/caminar2.png'),
                  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/edmond/caminar3.png')),
                 (pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/edmond/caminar_izq.png'),
                  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/edmond/caminar1_izq.png'),
                  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/edmond/caminar2_izq.png'),
                  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/edmond/caminar3_izq.png'))),

                ((pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/edmond/salto1.png'),
                  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/edmond/salto2.png'),
                  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/edmond/salto2.png')),
                 (pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/edmond/salto1_izq.png'),
                  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/edmond/salto2_izq.png'),
                  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/edmond/salto2_izq.png'))),

                ((pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/edmond/patada.png'),
                  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/edmond/patada1.png')),
                  (pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/edmond/patada_izq.png'),
                   pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/edmond/patada1_izq.png'))),

                 ((pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/edmond/puño.png'),
                   pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/edmond/puño1.png'),
                   pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/edmond/puño2.png')),
                  (pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/edmond/puño_izq.png'),
                   pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/edmond/puño1_izq.png'),
                   pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/edmond/puño2_izq.png'))),

                 ((pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/edmond/agacharse.png'),
                   pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/edmond/agacharse1.png')),
                   (pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/edmond/agacharse_izq.png'),
                    pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/edmond/agacharse1_izq.png'))),

                 ((pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/edmond/perdedor.png'),
                   pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/edmond/perdedor1.png'),
                   pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/edmond/perdedor2.png')),
                   (pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/edmond/perdedor_izq.png'),
                    pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/edmond/perdedor1_izq.png'),
                    pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/edmond/perdedor2_izq.png'))),

                 ((pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/edmond/victoria.png'),
                   pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/edmond/victoria1.png')),
                  (pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/edmond/victoria_izq.png'),
                   pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/edmond/victoria1_izq.png')))), {"heal": 1700, "kick": 10,"punch":8, "speed": 6}),
              ("Soviet Union","Zangief", pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/zangief_photo.png'),
              ((pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/zangief/quieto.png'),
                pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/zangief/quieto_izq.png')),
((pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/zangief/caminar.png'),
                 pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/zangief/caminar1.png'),
                 pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/zangief/caminar2.png'),
                 pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/zangief/caminar3.png')),
 (pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/zangief/caminar_izq.png'),
  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/zangief/caminar1_izq.png'),
  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/zangief/caminar2_izq.png'),
  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/zangief/caminar3_izq.png'))),
  
 ((pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/zangief/salto1.png'),
  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/zangief/salto2.png'),
  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/zangief/salto2.png')),
  (pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/zangief/salto1_izq.png'),
   pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/zangief/salto2_izq.png'),
   pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/zangief/salto2_izq.png'))),

 ((pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/zangief/patada.png'),
  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/zangief/patada1.png'),
  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/zangief/patada2.png')),
  (pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/zangief/patada_izq.png'),
   pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/zangief/patada1_izq.png'),
   pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/zangief/patada2_izq.png'))),

 ((pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/zangief/puño.png'),
  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/zangief/puño1.png'),
  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/zangief/puño2.png')),
  (pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/zangief/puño_izq.png'),
   pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/zangief/puño1_izq.png'),
   pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/zangief/puño2_izq.png'))),
   
   ((pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/zangief/agacharse.png'),
    pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/zangief/agacharse1.png')),
    (pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/zangief/agacharse_izq.png'),
    pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/zangief/agacharse1_izq.png'))),
    
    ((pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/zangief/perdedor.png'),
                 pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/zangief/perdedor1.png'),
                 pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/zangief/perdedor2.png')),
 (pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/zangief/perdedor_izq.png'),
  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/zangief/perdedor1_izq.png'),
  pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/zangief/perdedor2_izq.png'))),

               ((pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/zangief/victoria.png'),
                 pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/zangief/victoria1.png'),
                 pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/zangief/victoria2.png')),
                (pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/zangief/victoria_izq.png'),
                 pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/zangief/victoria1_izq.png'),
                 pygame.image.load(f'{os.path.dirname(__file__)}/imatges/personatges/zangief/victoria2_izq.png')))),{"heal": 1500, "kick": 17,"punch":15, "speed": 8})]